#!/bin/bash

NannyBotDir="$HOME/.config/nannybot"
BName=$( cat ""$NannyBotDir"/config.ini" | grep Bname | awk '{print $3}' )
icondir=""$NannyBotDir"/icons/$BName"

#copy prompt to home dir
cp -f /home/blink/.config/nannybot/prompts/mood_prompt /home/blink/.config/nannybot/current_prompt

notify-send "Hey there, How are you doing right now?

(Answer with Mod+Alt+N)" --icon="$icondir/notify_default.png" -t 30000
