#!/bin/bash

day=$(date +%A)
BName=$( cat ""$NannyBotDir"/config.ini" | grep Bname | awk '{print $3}' )
icondir="$HOME/.config/nannybot/icons/$BName"

case "$day" in
	Monday)
		notify-send "It's Monday, Please make sure to start the week off strong and healthy. Changing your sleeping scedual, and making it unstable is not good for your health" --icon="$icondir/notify_sad.png" -t 30000
		;;
	Tuesday)
		notify-send "Morning Sleepy-head!
Today is Tuesday! Make sure to go over what you have to do today before getting started!" --icon="$icondir/notify_default.png" -t 30000
		;;
	Wednesday)
		notify-send "Hey Sleepyhead! It's time to wake up!" --icon="$icondir/notify_sad.png" -t 30000
		;;
	Thursday)
		notify-send "Rise and shine! It's Thurday!
A late start is better than no start at all.

If you need anything I'm just a keyboard shortcut away!" --icon="$icondir/notify_default.png" -t 30000
		;;
	Friday)
		notify-send "Good Morning!
It's finally Friday! The final strech! Make sure to focus hard finishing the week strong!!

As always, I'm just a keyboard shortcut away!" --icon="$icondir/notify_smug.png" -t 30000
		;;
	Saturday)
		notify-send "Good Morning! It's finally the weekend! I hope you had a good rest last night." --icon="$icondir/notify_default.png" -t 60000
		;;
	Sunday)
		notify-send "Good Morning!
Today is Sunday! Make sure to check up on those around you that you love and care about! They are priceless, and without them you wouldn't be the person you are! Always cherish them." --icon="$icondir/notify_default.png" -t 60000
		;;
esac
